apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: api
          image: frissone/mvc-gd-api
---
apiVersion: v1
kind: Service
metadata:
  name: api-nodeport-srv
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
